### ISSUE TITLE
Reserved words in classes will prevent migration to Php7

### ISSUE THREAD

**Issue by luketarplin** [the-support-group/request-validator#5]
This codebase makes use of Php reserved words, which will prevent the migration of the codebase to Php7 environments see: http://php.net/manual/en/reserved.other-reserved-words.php namely; TheSupportGroup\Common\Validator\Rules\Boolean, could be others I haven't checked too far.

**Comment by forceedge01** [comment]
Thanks for logging this issue @luketarplin , will look into this 👍

**Comment by forceedge01** [comment]
@luketarplin Just ran tests using php7 and everything looks good. The reserved word is Bool rather than Boolean, closing this issue.
